/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.com.LevyatonRPGEngine.LevyBuild.Window;

import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author czech
 */
public class ShopGUi extends javax.swing.JPanel implements ActionListener{

    /**
     * Creates new form ShopGUi
     */
    
    Font mainFont;
    
    public ShopGUi() {
        initComponents();
        custom();
    }
    
    public void custom()
    {
        setClerkImage();
        buyButton.setName("Buy");
        buyButton.addActionListener(this);
        sellButton.setName("Sell");
        leaveButton.setName("Leave");
        sellButton.addActionListener(this);
        leaveButton.addActionListener(this);
        this.leaveButton.addActionListener(this);
        mainFont = this.shopText.getFont();
        this.setVisible(true);
    }

    
    public void setPlayerWealthText(String text)
    {
        this.pWealth.setText(text);
        revalidate();
        repaint();
    }
    
    public void setSelectedLabel(String name)
    {
        this.selectedPanelName.setText(name);
        this.selectedPanelName.setFont(mainFont);
        revalidate();
        repaint();
    }
    
    public void setSelectedButtons(ArrayList<JButton> buttons)
    {
        
        this.selectedPanel.removeAll();
       
        this.selectedPanel.setLayout(new BoxLayout(selectedPanel, BoxLayout.PAGE_AXIS));
        for(JButton b : buttons)
        {
           this.selectedPanel.add(Box.createRigidArea(new Dimension(0,20)));
           b.setText(b.getName());
           b.setFont(mainFont);
           b.setVisible(true);
           b.addActionListener(this);
           this.selectedPanel.add(b);
           

           revalidate();
           repaint();
        }
        
    }
    
    
    public void setClerkImage()
    {
        File f = new File(System.getProperty("user.dir") + "\\JeffTheKiller.png");
        BufferedImage image;
        
        try {
           
           image = ImageIO.read(f);
           image.s
           JLabel label = new JLabel(new ImageIcon(image));
           clerkPanel.add(label);
           
        } catch (IOException ex) {
             // handle exception...
        }   
        
    }
        
    
    
    public void setText(String text)
    {
        this.shopText.setText(text);
        revalidate();
        repaint();
    }
    
    public void writeText(String text) throws InterruptedException
    {
        char[] slowDown = text.toCharArray();
        /*
        for(char c : slowDown)
        {
        
            String s = Character.toString(c);
            this.battleText.append(s);
            Thread.sleep(100);
            
        }
       
        */
        this.shopText.append(text);
        revalidate();
        repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        clerkPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pWealth = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        shopText = new javax.swing.JTextArea();
        selectedPanel = new javax.swing.JPanel();
        buttonPanel = new javax.swing.JPanel();
        buyButton = new javax.swing.JButton();
        sellButton = new javax.swing.JButton();
        leaveButton = new javax.swing.JButton();
        selectedPanelName = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        clerkPanel.setBackground(new java.awt.Color(57, 57, 57));
        clerkPanel.setToolTipText("");
        clerkPanel.setName("clerkPanel"); // NOI18N
        clerkPanel.setLayout(new java.awt.GridBagLayout());

        pWealth.setBackground(new java.awt.Color(0, 0, 0));
        pWealth.setFont(new java.awt.Font("Old English Text MT", 0, 36)); // NOI18N
        pWealth.setForeground(new java.awt.Color(255, 0, 0));
        jScrollPane2.setViewportView(pWealth);
        pWealth.getAccessibleContext().setAccessibleName("pWealth");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 328;
        gridBagConstraints.ipady = 37;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(560, 0, 1, 500);
        clerkPanel.add(jScrollPane2, gridBagConstraints);

        add(clerkPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 620));
        clerkPanel.getAccessibleContext().setAccessibleName("clerkPanel");

        shopText.setBackground(new java.awt.Color(0, 0, 0));
        shopText.setColumns(20);
        shopText.setFont(new java.awt.Font("Old English Text MT", 0, 36)); // NOI18N
        shopText.setForeground(new java.awt.Color(255, 0, 0));
        shopText.setRows(5);
        shopText.setToolTipText("");
        shopText.setWrapStyleWord(true);
        jScrollPane1.setViewportView(shopText);
        shopText.getAccessibleContext().setAccessibleName("shopText");

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 850, 230));

        selectedPanel.setBackground(new java.awt.Color(60, 0, 0));
        selectedPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout selectedPanelLayout = new javax.swing.GroupLayout(selectedPanel);
        selectedPanel.setLayout(selectedPanelLayout);
        selectedPanelLayout.setHorizontalGroup(
            selectedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 346, Short.MAX_VALUE)
        );
        selectedPanelLayout.setVerticalGroup(
            selectedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 926, Short.MAX_VALUE)
        );

        add(selectedPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 70, 350, 930));
        selectedPanel.getAccessibleContext().setAccessibleName("selectedPanel");

        buttonPanel.setBackground(new java.awt.Color(82, 0, 0));

        buyButton.setBackground(new java.awt.Color(0, 0, 0));
        buyButton.setFont(new java.awt.Font("Old English Text MT", 0, 36)); // NOI18N
        buyButton.setForeground(new java.awt.Color(255, 255, 255));
        buyButton.setText("Buy");
        buyButton.setName("sellButton"); // NOI18N
        buyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyButtonActionPerformed(evt);
            }
        });

        sellButton.setBackground(new java.awt.Color(0, 0, 0));
        sellButton.setFont(new java.awt.Font("Old English Text MT", 0, 36)); // NOI18N
        sellButton.setForeground(new java.awt.Color(255, 255, 255));
        sellButton.setText("Sell");
        sellButton.setName("sellButton"); // NOI18N
        sellButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellButtonActionPerformed(evt);
            }
        });

        leaveButton.setBackground(new java.awt.Color(0, 0, 0));
        leaveButton.setFont(new java.awt.Font("Old English Text MT", 0, 36)); // NOI18N
        leaveButton.setForeground(new java.awt.Color(255, 255, 255));
        leaveButton.setText("Leave");
        leaveButton.setName("leaveButton"); // NOI18N
        leaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(buyButton)
                .addGap(88, 88, 88)
                .addComponent(sellButton)
                .addGap(83, 83, 83)
                .addComponent(leaveButton)
                .addContainerGap(171, Short.MAX_VALUE))
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buyButton)
                    .addComponent(sellButton)
                    .addComponent(leaveButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buyButton.getAccessibleContext().setAccessibleName("sellButton");
        sellButton.getAccessibleContext().setAccessibleName("sellButton");

        add(buttonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 850, 850, 130));
        buttonPanel.getAccessibleContext().setAccessibleName("buttonPanel");

        selectedPanelName.setBackground(new java.awt.Color(0, 0, 0));
        selectedPanelName.setFont(new java.awt.Font("Old English Text MT", 0, 36)); // NOI18N
        selectedPanelName.setForeground(new java.awt.Color(255, 255, 255));
        add(selectedPanelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 0, 350, 70));
        selectedPanelName.getAccessibleContext().setAccessibleName("selectedPanelName");
    }// </editor-fold>//GEN-END:initComponents

    private void buyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buyButtonActionPerformed

    private void sellButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sellButtonActionPerformed

    private void leaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaveButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_leaveButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton buyButton;
    private javax.swing.JPanel clerkPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton leaveButton;
    private javax.swing.JTextPane pWealth;
    private javax.swing.JPanel selectedPanel;
    private javax.swing.JTextField selectedPanelName;
    private javax.swing.JButton sellButton;
    private javax.swing.JTextArea shopText;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        
        try {
            
            MainFrame.buttonListener((JButton) e.getSource()); //To change body of generated methods, choose Tools | Templates.
        } catch (IOException ex) {
            Logger.getLogger(BattlePanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(BattlePanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (LineUnavailableException ex) {
            Logger.getLogger(ShopGUi.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(ShopGUi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
